In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'a

     Array can have multiple dimension
     
         1. 1d
         2. 2d
         3. 3d 
             etc 

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [5]:
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
type(arr)

numpy.ndarray

    1. Memory
    2. Speed

In [7]:
%%timeit

l1 = [i for i in range(10000)]
l2 = [i for i in range(10000)]
l3 = [l1[i]+l2[i] for i in range(len(l1))]


4.35 ms ± 70.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [10]:
a1 = np.arange(10)
a2 = np.arange(10)

In [11]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a1 + a2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
%%timeit

l1 = np.arange(10000)
l2 = np.arange(10000)
l3 = l1 + l2

54.6 µs ± 2.15 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### 1 D Array 

    Collection of elements 

In [15]:
arr = np.array([10, 12, 13, 14, 15, 20])

In [16]:
arr

array([10, 12, 13, 14, 15, 20])

In [17]:
type(arr)

numpy.ndarray

In [19]:
arr[0]

10

In [20]:
arr[-1]

20

In [21]:
len(arr)

6

In [22]:
arr[::-1]

array([20, 15, 14, 13, 12, 10])

In [23]:
arr

array([10, 12, 13, 14, 15, 20])

In [24]:
arr[3]

14

In [25]:
arr[3] = 400  # mutable

In [26]:
arr

array([ 10,  12,  13, 400,  15,  20])

In [27]:
arr.sum()

470

In [28]:
arr.mean()

78.33333333333333

In [29]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [30]:
print(dir(arr))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [31]:
np.median(arr)

14.0

In [32]:
arr.max()

400

In [33]:
arr.min()

10

In [34]:
arr.argmax()

3

In [35]:
arr

array([ 10,  12,  13, 400,  15,  20])

In [36]:
arr.argmin()

0

In [37]:
arr.sort()

In [38]:
arr

array([ 10,  12,  13,  15,  20, 400])

In [39]:
arr.argsort()

array([0, 1, 2, 3, 4, 5], dtype=int64)

In [40]:
from random import randint

In [42]:
arr = np.array([randint(1, 20) for i in range(20)])

In [43]:
arr

array([14,  5, 17, 13,  8, 17,  6, 12,  3,  4, 16,  7, 17, 10, 15, 11,  6,
       19,  4,  2])

In [44]:
arr.argsort()

array([19,  8, 18,  9,  1,  6, 16, 11,  4, 13, 15,  7,  3,  0, 14, 10,  5,
        2, 12, 17], dtype=int64)

In [45]:
arr[arr.argsort()]

array([ 2,  3,  4,  4,  5,  6,  6,  7,  8, 10, 11, 12, 13, 14, 15, 16, 17,
       17, 17, 19])

In [48]:
l = [1, 2, 3, 4, 10]

In [49]:
l[0]

1

In [51]:
l[[0, 1]]

TypeError: list indices must be integers or slices, not list

In [52]:
arr

array([14,  5, 17, 13,  8, 17,  6, 12,  3,  4, 16,  7, 17, 10, 15, 11,  6,
       19,  4,  2])

In [53]:
arr[[1, 5, 7, 8, 9]]

array([ 5, 17, 12,  3,  4])

In [54]:
np.array('python')

array('python', dtype='<U6')

In [55]:
arr

array([14,  5, 17, 13,  8, 17,  6, 12,  3,  4, 16,  7, 17, 10, 15, 11,  6,
       19,  4,  2])

In [56]:
arr.dtype

dtype('int32')

In [57]:
arr.ndim

1

In [58]:
arr.shape

(20,)

In [59]:
arr.size

20

In [60]:
np.array(['a', 'hello', 'bye'])

array(['a', 'hello', 'bye'], dtype='<U5')

In [64]:
np.array([1, 2, 3, 'hi', 12.34])

array(['1', '2', '3', 'hi', '12.34'], dtype='<U11')

In [67]:
a = np.array([1, 2, 3, 12.34])

In [68]:
a.dtype

dtype('float64')

### 2D Array 
        Collectionn of 1D array
            [
                [1, 2, 3, 4],
                [3, 4, 5, 5]
            ]
            
            Rows(n) and columns(m)
            total elements(size) --> n*m

In [69]:
n, m = int(input("\n ROWS --> ")), int(input("\n COLUMNS --> "))
arr = [[int(input()) for j in range(m)]for i in range(n)]


 ROWS --> 2

 COLUMNS --> 2
1
2
3
4


In [70]:
arr 

[[1, 2], [3, 4]]

In [71]:
arr2 = np.array([
    [1, 2, 3],
    [3, 4, 5]
])

In [72]:
arr2

array([[1, 2, 3],
       [3, 4, 5]])

In [73]:
arr2.shape

(2, 3)

In [74]:
arr2.size

6

In [75]:
arr2.dtype

dtype('int32')

In [76]:
arr2.ndim

2

In [78]:
b = np.array([[1, 2], [3, 4, 5], [5, 6, 7, 8]])

<ipython-input-78-e337c0f7c634>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  b = np.array([[1, 2], [3, 4, 5], [5, 6, 7, 8]])


In [79]:
b[0]

[1, 2]

In [80]:
b[1]

[3, 4, 5]

In [81]:
b[2]

[5, 6, 7, 8]

In [82]:
b

array([list([1, 2]), list([3, 4, 5]), list([5, 6, 7, 8])], dtype=object)

In [83]:
b.ndim

1

In [84]:
b.size

3

In [85]:
arr2

array([[1, 2, 3],
       [3, 4, 5]])

In [87]:
arr[0]

[1, 2]

In [88]:
arr2[0]

array([1, 2, 3])

In [91]:
arr[1][1]

4

In [93]:
arr2[1][1]

4

In [94]:
arr

[[1, 2], [3, 4]]

In [95]:
arr[::-1][::-1]

[[1, 2], [3, 4]]

In [98]:
arr[::-1]

[[3, 4], [1, 2]]

In [101]:
arr2[::-1]

array([[3, 4, 5],
       [1, 2, 3]])

In [102]:
arr2

array([[1, 2, 3],
       [3, 4, 5]])

In [105]:
arr2[::-1][::-1]

array([[1, 2, 3],
       [3, 4, 5]])

In [107]:
arr2[0, 1]
# arr[row_index/slicing, col_index/slicing]

2

In [108]:
arr[::-1, ::-1]

TypeError: list indices must be integers or slices, not tuple

In [109]:
arr2[::-1, ::-1]

array([[5, 4, 3],
       [3, 2, 1]])

In [110]:
arr2

array([[1, 2, 3],
       [3, 4, 5]])

In [113]:
arr2[::2, ::2]

array([[1, 3]])

In [114]:
#2d array, 3d array, comparisons